Repository gudwns1812/newstoss, pull requests merged in 2025-05, with the labels that each got.

#2 Test
  src/main/java/com/newstoss/auth/adapter/in/web/AuthController.java
  src/main/java/com/newstoss/auth/adapter/in/web/dto/requestDTO/LoginDTO.java
  src/main/java/com/newstoss/auth/application/AuthService.java
  src/main/java/com/newstoss/auth/application/command/LoginService.java
  src/main/java/com/newstoss/member/adapter/in/web/MemberController.java
  src/main/java/com/newstoss/member/adapter/in/web/dto/requestDTO/AddressDTO.java
  src/main/java/com/newstoss/member/adapter/in/web/dto/requestDTO/SignupRequestDTO.java
  src/main/java/com/newstoss/member/adapter/out/persistence/JPAMemberRepository.java
  src/main/java/com/newstoss/member/adapter/out/persistence/MemberAdapter.java
  src/main/java/com/newstoss/member/application/MemberService.java
  src/main/java/com/newstoss/member/application/command/SignupService.java
  src/main/java/com/newstoss/member/application/command/WithdrawService.java
  src/main/java/com/newstoss/member/application/query/GetMemberService.java
  src/main/java/com/newstoss/member/domain/Address.java
  src/main/java/com/newstoss/member/domain/Member.java
  src/main/java/com/newstoss/member/domain/MemberCommandPort.java
  src/main/java/com/newstoss/member/domain/MemberQueryPort.java
Labels: 준영

#5 [FIX] security 모든 경로 허용(개발용)
  src/main/java/com/newstoss/global/config/SecurityConfig.java
  src/main/java/com/newstoss/member/adapter/in/web/MemberController.java
Labels: 🐛 fix, 준영

#9 [FEAT] id중복 체크 api 생성
  src/main/java/com/newstoss/member/adapter/in/web/MemberController.java
  src/main/java/com/newstoss/member/adapter/in/web/dto/requestDTO/DuplicateDTO.java
  src/main/java/com/newstoss/member/application/MemberService.java
  src/main/java/com/newstoss/member/application/command/SignupService.java
  src/main/java/com/newstoss/member/application/query/DuplicateCheck.java
Labels: ✨ feature, 준영

#10 Feat/#08 cd
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  Dockerfile
  src/test/java/com/newstoss/NewstossApplicationTests.java
Labels: ✨ feature, 장우

#13 [FIX] CD, Dockerfile 수정
  .github/workflows/ci.yml
  Dockerfile
Labels: 🐛 fix, 장우

#17 [FIX] cd 수정 4
  .github/workflows/cd.yml
Labels: 🐛 fix, 장우

#18 Feat/#7 news
  src/main/java/com/newstoss/global/errorcode/NewsErrorCode.java
  src/main/java/com/newstoss/global/healthcheck/MLHealthCheck.java
  src/main/java/com/newstoss/member/adapter/in/web/MemberController.java
  src/main/java/com/newstoss/news/adapter/in/web/NewsController.java
  src/main/java/com/newstoss/news/adapter/in/web/dto/NewsDTO.java
  src/main/java/com/newstoss/news/adapter/in/web/dto/RelatedNewsDTO.java
  src/main/java/com/newstoss/news/adapter/in/web/dto/RelatedStockDTO.java
  src/main/java/com/newstoss/news/adapter/out/MLNewsAdapter.java
  src/main/java/com/newstoss/news/adapter/out/dto/MLNewsDTO.java
  src/main/java/com/newstoss/news/adapter/out/dto/MLRelatedNewsDTO.java
  src/main/java/com/newstoss/news/adapter/out/dto/MLRelatedStockDTO.java
  src/main/java/com/newstoss/news/application/NewsService.java
  src/main/java/com/newstoss/news/application/port/in/GetNewsDetailUseCase.java
  src/main/java/com/newstoss/news/application/port/in/GetRealTimeNewsUseCase.java
  src/main/java/com/newstoss/news/application/port/in/GetRelatedNewsUseCase.java
  src/main/java/com/newstoss/news/application/port/in/GetRelatedStocksUseCase.java
  src/main/java/com/newstoss/news/application/port/out/MLNewsPort.java
  src/main/java/com/newstoss/news/application/service/GetDetailNews.java
  src/main/java/com/newstoss/news/application/service/GetRealTimeNews.java
  src/main/java/com/newstoss/news/application/service/GetRelatedNews.java
  src/main/java/com/newstoss/news/application/service/GetRelatedStocks.java
  src/main/java/com/newstoss/news/news.txt
Labels: ✨ feature, 준영

#19 [FIX] cd 수정 5
  .github/workflows/cd.yml
Labels: 🐛 fix, 장우

#21 [FIX] cd 수정 7
  .github/workflows/cd.yml
Labels: 🐛 fix, 장우

#26 [FIX] ci 최적화
  .github/workflows/ci.yml
  Dockerfile
Labels: 🐛 fix, 장우

#28 [FIX] jwt 에러 핸들링 추가 및 password 해시 처리
  src/main/java/com/newstoss/auth/application/command/LoginService.java
  src/main/java/com/newstoss/global/config/PasswordEncoderConfig.java
  src/main/java/com/newstoss/global/config/SecurityConfig.java
  src/main/java/com/newstoss/global/errorcode/JwtErrorCode.java
  src/main/java/com/newstoss/global/jwt/JwtAccessDeniedHandler.java
  src/main/java/com/newstoss/global/jwt/JwtAuthenticationEntryPoint.java
  src/main/java/com/newstoss/global/jwt/JwtProvider.java
  src/main/java/com/newstoss/member/adapter/out/persistence/JpaMemberRepository.java
  src/main/java/com/newstoss/member/adapter/out/persistence/MemberAdapter.java
  src/main/java/com/newstoss/member/application/command/SignupService.java
  src/main/java/com/newstoss/member/domain/Member.java
Labels: 🐛 fix, 준영

#29 [FIX] 증권 api 수정
  build.gradle
  src/main/java/com/newstoss/global/config/AppConfig.java
  src/main/java/com/newstoss/global/init/StockInit.java
  src/main/java/com/newstoss/global/kis/KisToken.java
  src/main/java/com/newstoss/global/kis/KisTokenManager.java
  src/main/java/com/newstoss/global/kis/TokenSchedular.java
  src/main/java/com/newstoss/stock/adapter/inbound/api/StockApiController.java
  src/main/java/com/newstoss/stock/adapter/inbound/api/v1/StockApiController.java
  src/main/java/com/newstoss/stock/adapter/inbound/api/v1/kis/StockKisController.java
  src/main/java/com/newstoss/stock/adapter/inbound/dto/request/StockCountRequestDto.java
  src/main/java/com/newstoss/stock/adapter/inbound/dto/response/CategoriesResponseDto.java
  src/main/java/com/newstoss/stock/adapter/inbound/dto/response/CategoryPageResponseDto.java
  src/main/java/com/newstoss/stock/adapter/inbound/dto/response/CategoryStockResponseDto.java
  src/main/java/com/newstoss/stock/adapter/inbound/dto/response/IndicesResponseDto.java
  src/main/java/com/newstoss/stock/adapter/inbound/dto/response/SearchResponseDto.java
  src/main/java/com/newstoss/stock/adapter/inbound/dto/response/StockPriceResponseDto.java
  src/main/java/com/newstoss/stock/adapter/outbound/kis/dto/KisHTS20Stock.java
  src/main/java/com/newstoss/stock/adapter/outbound/persistence/repository/StockRepository.java
  src/main/java/com/newstoss/stock/adapter/outbound/persistence/repository/StockRepositoryCustomImpl.java
  src/main/java/com/newstoss/stock/adapter/outbound/persistence/repository/StockRepositoryImpl.java
  src/main/java/com/newstoss/stock/application/GetIndiceInfoService.java
  src/main/java/com/newstoss/stock/application/GetKisStockService.java
  src/main/java/com/newstoss/stock/application/GetPopularStockService.java
  src/main/java/com/newstoss/stock/application/StockCommandService.java
  src/main/java/com/newstoss/stock/application/StockQueryService.java
  src/main/java/com/newstoss/stock/application/port/in/GetCategoryUseCase.java
  src/main/java/com/newstoss/stock/application/port/in/GetStockInfoUseCase.java
  src/main/java/com/newstoss/stock/application/port/in/SearchStockUseCase.java
  src/main/java/com/newstoss/stock/application/port/in/UpdateStockSearchCount.java
  src/main/java/com/newstoss/stock/application/port/in/UpdateStockUseCase.java
  src/main/java/com/newstoss/stock/application/port/out/StockRepositoryCustom.java
  src/main/java/com/newstoss/stock/entity/Stock.java
  src/test/java/com/newstoss/global/kis/KisTokenManagerTest.java
  src/test/java/com/newstoss/stock/adapter/inbound/api/v1/StockApiControllerTest.java
  src/test/java/com/newstoss/stock/adapter/inbound/api/v2/StockKRXControllerTest.java
  src/test/java/com/newstoss/stock/adapter/outbound/persistence/repository/SearchStockRepositoryImplTest.java
  src/test/java/com/newstoss/stock/application/StockQueryServiceTest.java
Labels: 🐛 fix, 형준

#32 현재 보고 있는 관심 그룹 변경 api 추가 및 redis설정
  build.gradle
  src/main/java/com/newstoss/global/config/RedisConfig.java
  src/main/java/com/newstoss/global/redis/RedisNewsPublisher.java
  src/main/java/com/newstoss/global/redis/RedisNewsSubscriber.java
  src/main/java/com/newstoss/member/adapter/in/web/MemberController.java
  src/main/java/com/newstoss/member/adapter/in/web/dto/requestDTO/FgOffsetDTO.java
  src/main/java/com/newstoss/member/application/MemberService.java
  src/main/java/com/newstoss/member/application/command/FgOffsetService.java
  src/main/java/com/newstoss/member/domain/Member.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/NewsSseController.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/SseEmitters.java
  src/main/java/com/newstoss/news/application/scheduler/RealTimeNewsScheduler.java
  src/main/java/com/newstoss/news/application/service/GetRealTimeNewsWithSSE.java
Labels: 🐛 fix, ✨ feature, 준영

#35 [FIX] JWT 포함 정보 수정
  src/main/java/com/newstoss/auth/application/command/LoginService.java
  src/main/java/com/newstoss/global/jwt/JwtProvider.java
Labels: 🐛 fix, 준영

#36 Feat/#7 news
  src/main/java/com/newstoss/news/adapter/in/web/controller/NewsControllerV1.java
  src/main/java/com/newstoss/news/adapter/in/web/controller/NewsControllerV2.java
  src/main/java/com/newstoss/news/adapter/in/web/dto/common/RelatedNewsDTO.java
  src/main/java/com/newstoss/news/adapter/in/web/dto/common/RelatedReportDTO.java
  src/main/java/com/newstoss/news/adapter/in/web/dto/common/RelatedStockDTO.java
  src/main/java/com/newstoss/news/adapter/in/web/dto/v1/NewsDTOv1.java
  src/main/java/com/newstoss/news/adapter/in/web/dto/v2/NewsDTOv2.java
  src/main/java/com/newstoss/news/adapter/out/dto/v1/MLNewsDTOv1.java
  src/main/java/com/newstoss/news/adapter/out/dto/v2/MLNewsDTOv2.java
  src/main/java/com/newstoss/news/adapter/out/ml/v1/MLNewsRelatedAdapterV1V1.java
  src/main/java/com/newstoss/news/adapter/out/ml/v2/MLNewsRelatedAdapterV2.java
  src/main/java/com/newstoss/news/application/NewsServiceV1.java
  src/main/java/com/newstoss/news/application/NewsServiceV2.java
  src/main/java/com/newstoss/news/application/port/in/GetNewsDetailUseCase.java
  src/main/java/com/newstoss/news/application/port/in/GetRealTimeNewsUseCase.java
  src/main/java/com/newstoss/news/application/port/in/GetRelatedNewsUseCase.java
  src/main/java/com/newstoss/news/application/port/in/GetRelatedReportUseCase.java
  src/main/java/com/newstoss/news/application/port/in/GetRelatedStocksUseCase.java
  src/main/java/com/newstoss/news/application/port/in/v1/GetNewsDetailUseCaseV1.java
  src/main/java/com/newstoss/news/application/port/in/v1/GetRealTimeNewsUseCaseV1.java
  src/main/java/com/newstoss/news/application/port/in/v2/GetNewsDetailUseCaseV2.java
  src/main/java/com/newstoss/news/application/port/in/v2/GetRealTimeNewsUseCaseV2.java
  src/main/java/com/newstoss/news/application/port/out/MLNewsRelatedPortV1.java
  src/main/java/com/newstoss/news/application/port/out/MLNewsRelatedPortV2.java
  src/main/java/com/newstoss/news/application/service/GetDetailNews.java
  src/main/java/com/newstoss/news/application/service/GetRealTimeNews.java
  src/main/java/com/newstoss/news/application/service/GetRealTimeNewsWithSSE.java
  src/main/java/com/newstoss/news/application/service/GetRelatedNews.java
  src/main/java/com/newstoss/news/application/service/GetRelatedReport.java
  src/main/java/com/newstoss/news/application/service/GetRelatedStocks.java
  src/main/java/com/newstoss/news/application/service/v1/GetDetailNewsV1.java
  src/main/java/com/newstoss/news/application/service/v1/GetRealTimeNewsV1.java
  src/main/java/com/newstoss/news/application/service/v1/NewsDTOv1Mapper.java
  src/main/java/com/newstoss/news/application/service/v2/GetDetailNewsV2.java
  src/main/java/com/newstoss/news/application/service/v2/GetRealTimeNewsV2.java
  src/main/java/com/newstoss/news/application/service/v2/NewsDTOv2Mapper.java
Labels: 🐛 fix, 준영

#40 [FIX] 파일 구조 변경
  src/main/java/com/newstoss/news/adapter/in/web/controller/NewsControllerV1.java
  src/main/java/com/newstoss/news/adapter/in/web/controller/NewsControllerV2.java
  src/main/java/com/newstoss/news/application/impl/GetRealTimeNewsWithSSE.java
  src/main/java/com/newstoss/news/application/impl/GetRelatedNews.java
  src/main/java/com/newstoss/news/application/impl/GetRelatedReport.java
  src/main/java/com/newstoss/news/application/impl/GetRelatedStocks.java
  src/main/java/com/newstoss/news/application/impl/v1/GetDetailNewsV1.java
  src/main/java/com/newstoss/news/application/impl/v1/GetRealTimeNewsV1.java
  src/main/java/com/newstoss/news/application/impl/v1/NewsDTOv1Mapper.java
  src/main/java/com/newstoss/news/application/impl/v2/GetDetailNewsV2.java
  src/main/java/com/newstoss/news/application/impl/v2/GetRealTimeNewsV2.java
  src/main/java/com/newstoss/news/application/impl/v2/NewsDTOv2Mapper.java
  src/main/java/com/newstoss/news/application/port/in/ml/GetRelatedNewsUseCase.java
  src/main/java/com/newstoss/news/application/port/in/ml/GetRelatedReportUseCase.java
  src/main/java/com/newstoss/news/application/port/in/ml/GetRelatedStocksUseCase.java
  src/main/java/com/newstoss/news/application/port/in/ml/v1/GetNewsDetailUseCaseV1.java
  src/main/java/com/newstoss/news/application/port/in/ml/v1/GetRealTimeNewsUseCaseV1.java
  src/main/java/com/newstoss/news/application/port/in/ml/v2/GetNewsDetailUseCaseV2.java
  src/main/java/com/newstoss/news/application/port/in/ml/v2/GetRealTimeNewsUseCaseV2.java
  src/main/java/com/newstoss/news/application/service/NewsServiceV1.java
  src/main/java/com/newstoss/news/application/service/NewsServiceV2.java
  src/main/java/com/newstoss/news/domain/NewsScrap.java
Labels: 🐛 fix, 준영

#41 [FIX] ci, cd 수정
  .github/workflows/cd.yml
  .github/workflows/ci.yml
Labels: 🐛 fix, 장우
