Repository gudwns1812/newstoss, pull requests merged in 2025-06, with the labels that each got.

#46 [FIX] cd.yml 수정
  .github/workflows/cd.yml
Labels: 🐛 fix, 장우

#56 [FEAT] 관심종목 API 추가
  src/main/java/com/newstoss/favorite/FavoriteController.java
  src/main/java/com/newstoss/favorite/FavoriteGroup/Favorite.java
  src/main/java/com/newstoss/favorite/FavoriteGroup/FavoriteController.java
  src/main/java/com/newstoss/favorite/FavoriteGroup/FavoriteRepository.java
  src/main/java/com/newstoss/favorite/FavoriteGroup/FavoriteService.java
  src/main/java/com/newstoss/favorite/FavoriteGroup/favorite.txt
  src/main/java/com/newstoss/favorite/FavoriteRepository.java
  src/main/java/com/newstoss/favorite/FavoriteService.java
  src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStock.java
  src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStockController.java
  src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStockRepository.java
  src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStockService.java
  src/main/java/com/newstoss/favorite/FavoriteStock/dto/FavoriteStockResponseDto.java
  src/main/java/com/newstoss/favorite/FavoriteStock/dto/UpdateStockSequenceRequest.java
  src/main/java/com/newstoss/global/config/SecurityConfig.java
Labels: ✨ feature, 장우

#59 [FEAT] 뉴스 db저장 및 redis,sse설정
  src/main/java/com/newstoss/global/config/RedisConfig.java
  src/main/java/com/newstoss/global/redis/NewsRedisSubscriber.java
  src/main/java/com/newstoss/global/redis/RedisTestPublisher.java
  src/main/java/com/newstoss/news2/adapter/in/NewsController.java
  src/main/java/com/newstoss/news2/adapter/in/NewsDTO.java
  src/main/java/com/newstoss/news2/adapter/out/NewsClient.java
  src/main/java/com/newstoss/news2/adapter/out/NewsRepository.java
  src/main/java/com/newstoss/news2/application/NewsService.java
  src/main/java/com/newstoss/news2/domain/NewsEntity.java
Labels: ✨ feature, 준영

#68 [FIX] 캘린더, 관심종목 수정
  src/main/java/com/newstoss/calender/CalendarController.java
  src/main/java/com/newstoss/favorite/FavoriteGroup/FavoriteController.java
Labels: 🐛 fix, 장우

#70 Feat/#7 news
  build.gradle
  src/main/java/com/newstoss/global/errorcode/ScrapErrorCode.java
  src/main/java/com/newstoss/global/kis/TokenScheduler.java
  src/main/java/com/newstoss/global/redis/NewsRedisSubscriber.java
  src/main/java/com/newstoss/news/adapter/out/dto/scrap/ScrapResponseDTO.java
  src/main/java/com/newstoss/news/adapter/out/scrap/JpaNewsScrapRepository.java
  src/main/java/com/newstoss/news/adapter/out/scrap/ScrapNewsAdapter.java
  src/main/java/com/newstoss/news/application/impl/scrap/SaveScrapNews.java
  src/main/java/com/newstoss/news/domain/NewsEntity.java
  src/main/java/com/newstoss/news/domain/NewsScrap.java
  src/main/java/com/newstoss/news2/adapter/CsvRunner.java
  src/main/java/com/newstoss/news2/adapter/out/NewsRepository.java
  src/main/java/com/newstoss/news2/application/CsvImportService.java
  src/main/java/com/newstoss/news2/application/NewsService.java
  src/main/resources/logback-spring.xml
  src/test/java/com/newstoss/news/TestCode/PerformanceTestHelper.java
  src/test/java/com/newstoss/news/TestCode/many/ManyToManyPerformanceTest.java
  src/test/java/com/newstoss/news/TestCode/one/ManyToOnePerformanceTest.java
  src/test/java/com/newstoss/news/domain/many/MemberScrapTest.java
  src/test/resources/application-test.yml
Labels: ✨ feature, 준영

#71 [FIX] redis설정 변경
  src/main/java/com/newstoss/global/redis/NewsRedisSubscriber.java
Labels: 🐛 fix, 준영

#73 [FIX] redis설정
  src/main/java/com/newstoss/news/adapter/in/web/sse/NewsSseController.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/SseEmitters.java
Labels: 🐛 fix, 준영

#74 [FEAT] CORS 설정
  src/main/java/com/newstoss/news/adapter/in/web/sse/NewsSseController.java
Labels: 🐛 fix, 준영

#79 [FEAT] 관심그룹 이름 변경 기능 추가
  src/main/java/com/newstoss/favorite/FavoriteGroup/FavoriteController.java
  src/main/java/com/newstoss/favorite/FavoriteGroup/FavoriteService.java
Labels: ✨ feature, 장우

#80 [FIX] SSE 수정 및 ML api 매칭
  src/main/java/com/newstoss/global/config/RedisConfig.java
  src/main/java/com/newstoss/global/errorcode/RedisAndSseErrorCode.java
  src/main/java/com/newstoss/global/redis/RedisTestPublisher.java
  src/main/java/com/newstoss/news/adapter/in/web/controller/NewsControllerV2.java
  src/main/java/com/newstoss/news/adapter/in/web/controller/NewsSseController.java
  src/main/java/com/newstoss/news/adapter/in/web/dto/news/v2/NewsMathRelatedDTO.java
  src/main/java/com/newstoss/news/adapter/in/web/dto/news/v2/NewsMetaDataDTO.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/SseEmitters.java
  src/main/java/com/newstoss/news/adapter/out/dto/v2/MLNewsMataDataDTOv2.java
  src/main/java/com/newstoss/news/adapter/out/news/v2/MLNewsAdapterV2.java
  src/main/java/com/newstoss/news/adapter/out/redis/HighlightNewsCache.java
  src/main/java/com/newstoss/news/adapter/out/redis/HighlightNewsScheduler.java
  src/main/java/com/newstoss/news/adapter/out/redis/NewsRedisSubscriber.java
  src/main/java/com/newstoss/news/adapter/out/redis/RedisTestPublisher.java
  src/main/java/com/newstoss/news/application/impl/news/GetRealTimeNewsWithSSE.java
  src/main/java/com/newstoss/news/application/impl/news/v2/GetNewsMataDataV2.java
  src/main/java/com/newstoss/news/application/impl/news/v2/GetRelatedNewsV2.java
  src/main/java/com/newstoss/news/application/impl/news/v2/GetRelatedStockV2.java
  src/main/java/com/newstoss/news/application/impl/news/v2/MatchNewsWithRelatedService.java
  src/main/java/com/newstoss/news/application/impl/news/v2/NewsDTOv2Mapper.java
  src/main/java/com/newstoss/news/application/impl/redis/HighlightNewsCacheService.java
  src/main/java/com/newstoss/news/application/port/in/ml/v2/GetNewsMataDataUseCaseV2.java
  src/main/java/com/newstoss/news/application/port/in/ml/v2/GetRelatedStockUseCaseV2.java
  src/main/java/com/newstoss/news/application/port/in/ml/v2/MatchNewsWithRelatedUseCase.java
  src/main/java/com/newstoss/news/application/port/in/redis/HighlightNewsCacheUseCase.java
  src/main/java/com/newstoss/news/application/port/out/ml/v2/MLNewsPortV2.java
  src/main/java/com/newstoss/news/application/port/out/redis/HighlightNewsCachePort.java
  src/main/java/com/newstoss/news/application/service/NewsServiceV2.java
Labels: 🐛 fix, 준영

#89 [FEAT] invest_score 수정 api 구현
  src/main/java/com/newstoss/member/adapter/in/web/MemberController.java
  src/main/java/com/newstoss/member/application/MemberService.java
  src/main/java/com/newstoss/member/application/in/command/InvestScoreService.java
  src/main/java/com/newstoss/member/domain/Member.java
Labels: ✨ feature, 준영

#90 [FIX] prod확인용 로그 추가
  src/main/java/com/newstoss/news/adapter/out/redis/HighlightNewsScheduler.java
Labels: 🐛 fix, 준영

#96 ML api endpoint 수정으로 인한 변경
  src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV1.java
  src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java
  src/main/java/com/newstoss/news/adapter/out/news/v2/MLNewsAdapterV2.java
Labels: 🐛 fix, 준영

#99 [FIX} SSE emitter 설정
  src/main/java/com/newstoss/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/NewsSseController.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/SseEmitters.java
  src/main/java/com/newstoss/news/adapter/out/redis/NewsRedisSubscriber.java
  src/test/java/com/newstoss/sse/SseEmittersTest.java
Labels: 🐛 fix, 준영

#103 [FIX]TomCat 에러 잡기
  src/main/java/com/newstoss/global/handler/GlobalExceptionHandler.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/SseEmitters.java
Labels: 🐛 fix, 준영

#107 챗봇 api
  src/main/java/com/newstoss/global/config/RedisConfig.java
  src/main/java/com/newstoss/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/RealTimeNewsDTO.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/ChatStreamEmitters.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/NewsSseEmitters.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/controller/ChatSseController.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/controller/NewsSseController.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/dto/ChatStreamRequest.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/dto/ChatStreamResponse.java
  src/main/java/com/newstoss/news/adapter/out/news/v2/MLNewsAdapterV2.java
  src/main/java/com/newstoss/news/adapter/out/redis/chatbot/ChatRedisSubscriber.java
  src/main/java/com/newstoss/news/adapter/out/redis/highlight/HighlightNewsCacheImpl.java
  src/main/java/com/newstoss/news/adapter/out/redis/highlight/HighlightNewsScheduler.java
  src/main/java/com/newstoss/news/adapter/out/redis/highlight/NewsRedisSubscriber.java
  src/main/java/com/newstoss/news/application/news/v2/port/out/MLNewsPortV2.java
  src/main/java/com/newstoss/news/application/redis/ChatStreamService.java
  src/test/java/com/newstoss/news/TestCode/PerformanceTestHelper.java
  src/test/java/com/newstoss/news/TestCode/many/ManyToManyPerformanceTest.java
  src/test/java/com/newstoss/news/TestCode/one/ManyToOnePerformanceTest.java
  src/test/java/com/newstoss/news/domain/many/MemberScrapTest.java
  src/test/java/com/newstoss/sse/NewsSseEmittersTest.java
  src/test/resources/application-test.yml
Labels: ✨ feature, 준영

#108 [FIX] dto Key 값 성정
  src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/ChatMessage.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/controller/ChatSseController.java
  src/main/java/com/newstoss/news/application/redis/ChatStreamService.java
Labels: 🐛 fix, 준영

#112 [FEAT] 챗봇 api
  src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/RealTimeNewsDTO.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/controller/ChatSseController.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/dto/ChatStreamRequest.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/dto/ChatStreamResponse.java
  src/main/java/com/newstoss/news/adapter/out/news/v2/MLNewsAdapterV2.java
  src/main/java/com/newstoss/news/adapter/out/redis/chatbot/ChatRedisSubscriber.java
  src/main/java/com/newstoss/news/application/news/v2/port/out/MLNewsPortV2.java
Labels: ✨ feature, 준영

#114 [FEAT] 뉴스 로그 추가
  .github/workflows/cd.yml
  Dockerfile
  src/main/java/com/newstoss/news/application/news/v2/impl/ml/GetDetailNewsV2.java
  src/main/resources/logback-spring.xml
Labels: ✨ feature, 장우

#119 [FIX] log설정
  src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java
  src/main/java/com/newstoss/news/application/news/service/NewsServiceV2.java
  src/main/java/com/newstoss/news/application/news/v2/impl/ml/GetDetailNewsV2.java
  src/main/java/com/newstoss/news/application/news/v2/port/in/GetNewsDetailUseCaseV2.java
  src/main/resources/logback-spring.xml
Labels: 🐛 fix, 준영

#122 Update KisApiStreamConsumer.java
  src/main/java/com/newstoss/stock/application/stream/KisApiStreamConsumer.java
Labels: 🐛 fix, 장우

#123 [FIX] 뉴스 로그 파싱 수정
  src/main/java/com/newstoss/news/application/news/service/NewsLogsService.java
Labels: 🐛 fix, 장우

#124 [FIX] 하이라이트 뉴스 주석 제거
  src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java
Labels: 🐛 fix, 장우

#126 [FIX] SecurityConfig 수정 (JwtAuthenticationFilter 테스트용)
  src/main/java/com/newstoss/global/config/SecurityConfig.java
Labels: 🐛 fix, 장우

#128 [FIX] 뉴스 컨트롤러에서 직접 SecurityContextHolder 가져오기
  src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java
Labels: 🐛 fix, 장우

#129 [FIX] 원상태 되돌리기
  src/main/java/com/newstoss/global/config/SecurityConfig.java
  src/main/java/com/newstoss/global/jwt/JwtAuthenticationFilter.java
Labels: 🐛 fix, 장우

#130 [FIX] 원상태 복귀
  src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java
  src/main/java/com/newstoss/news/application/news/service/NewsServiceV2.java
  src/main/java/com/newstoss/news/application/news/v2/impl/ml/GetDetailNewsV2.java
  src/main/java/com/newstoss/news/application/news/v2/port/in/GetNewsDetailUseCaseV2.java
Labels: 🐛 fix, 장우

#133 [FIX] SecurityConfig requestMatchers 조건 바꾸기
  src/main/java/com/newstoss/global/config/SecurityConfig.java
Labels: 🐛 fix, 장우

#135 [FIX] userAccount로 변경
  src/main/java/com/newstoss/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/newstoss/member/application/in/command/CustomUserDetailsService.java
  src/main/java/com/newstoss/member/domain/Member.java
  src/main/java/com/newstoss/member/domain/UserAccount.java
  src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java
Labels: 🐛 fix, 장우

#136 [FIX] 쿠키밸류로 값 끄네기
  src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java
Labels: 🐛 fix, 장우

#138 [FIX] crossorigin 조건 변경
  src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java
Labels: 🐛 fix, 장우

#142 [FIX] samesite 설정
  src/main/java/com/newstoss/auth/adapter/in/web/AuthController.java
Labels: 🐛 fix, 준영

#143 [FIX] CORS 설정
  src/main/java/com/newstoss/global/config/WebConfig.java
Labels: 🐛 fix, 준영

#148 Juneyoung
  .github/workflows/cd.yml
  src/main/java/com/newstoss/global/config/SecurityConfig.java
  src/main/java/com/newstoss/global/config/WebConfig.java
  src/main/java/com/newstoss/stock/adapter/outbound/persistence/init/StockHistoryInitializer.java
  src/main/java/com/newstoss/stock/adapter/outbound/persistence/repository/StockHistoryRepository.java
  src/main/java/com/newstoss/stock/entity/StockHistory.java
Labels: 🐛 fix, 준영

#149 [FIX] 긴급 복구
  src/main/java/com/newstoss/stock/application/V1/StockInfoService.java
Labels: 🐛 fix, 준영

#150 Juneyoung
  .gitignore
  git
  src/main/java/com/newstoss/global/config/SecurityConfig.java
  src/main/java/com/newstoss/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/newstoss/global/jwt/JwtProvider.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/controller/SseController.java
Labels: 🐛 fix, 준영

#151 [FIX] endpoint 수정
  src/main/java/com/newstoss/global/config/SecurityConfig.java
  src/main/java/com/newstoss/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/newstoss/global/jwt/JwtProvider.java
Labels: 🐛 fix, 준영

#152 [FIX] 챗봇 GET으로 변경
  src/main/java/com/newstoss/news/adapter/in/web/sse/controller/SseController.java
  src/main/java/com/newstoss/news/application/redis/ChatStreamService.java
Labels: 🐛 fix, 준영

#154 [FIX] 프로메테우스 설정
  src/main/java/com/newstoss/global/config/SecurityConfig.java
Labels: 🐛 fix, 준영

#155 [FIX] 프로메테우스 설정
  src/main/java/com/newstoss/global/config/SecurityConfig.java
Labels: 🐛 fix, 준영

#157 [TEST] 챗봇 테스트
  src/main/java/com/newstoss/news/adapter/in/web/sse/controller/SseController.java
  src/main/java/com/newstoss/news/adapter/out/redis/subscriber/ChatRedisSubscriber.java
Labels: 🧪 test, 준영

#161 [FIX] DTO 수정
  src/main/java/com/newstoss/news/application/news/v2/impl/NewsDTOv2Mapper.java
Labels: 🐛 fix, 준영

#163 [TEST] 챗봇 테스트
  src/main/java/com/newstoss/news/adapter/out/redis/subscriber/ChatRedisSubscriber.java
Labels: 🧪 test, 준영

#164 [Test] 챗봇 테스트
  src/main/java/com/newstoss/news/adapter/out/redis/subscriber/ChatRedisSubscriber.java
Labels: 🧪 test, 준영

#165 [FIX]일봉 2000일로 수정, 주봉 안되던거 수정
  src/main/java/com/newstoss/stock/application/V1/StockInfoService.java
Labels: 🐛 fix, 장우

#167 [Test] 챗봇 테스트
  src/main/java/com/newstoss/global/config/SecurityConfig.java
  src/main/java/com/newstoss/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/controller/SseController.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/emitter/ChatStreamEmitters.java
  src/main/java/com/newstoss/news/adapter/out/redis/subscriber/ChatRedisSubscriber.java
  src/main/java/com/newstoss/news/application/redis/ChatStreamService.java
Labels: 🧪 test, 준영

#168 [FEAT] 캘린더 마켓 구분 조회 기능 추가
  src/main/java/com/newstoss/calender/CalendarController.java
  src/main/java/com/newstoss/calender/CalendarRepository.java
  src/main/java/com/newstoss/global/errorcode/ScrapErrorCode.java
Labels: ✨ feature, 장우

#171 [FIX] 중복 처리 로직 수정
  src/main/java/com/newstoss/news/adapter/out/redis/subscriber/ChatRedisSubscriber.java
Labels: 🐛 fix, 준영

#173 [FIX] 뉴스 스크랩 ml API로 연동
  src/main/java/com/newstoss/news/adapter/in/web/scrap/controller/ScrapNewsController.java
  src/main/java/com/newstoss/news/adapter/in/web/scrap/dto/ExternalNewsDTO.java
  src/main/java/com/newstoss/news/adapter/out/scrap/ScrapNewsAdapter.java
  src/main/java/com/newstoss/news/adapter/out/scrap/repository/JpaNewsScrapRepository.java
  src/main/java/com/newstoss/news/application/scrap/impl/GetScrapNewsList.java
  src/main/java/com/newstoss/news/application/scrap/impl/SaveScrapNews.java
  src/main/java/com/newstoss/news/domain/NewsScrap.java
Labels: 🐛 fix, 장우

#179 [FIX] 챗봇 로그 추가
  src/main/java/com/newstoss/news/adapter/out/redis/subscriber/ChatRedisSubscriber.java
Labels: 🐛 fix, 준영

#182 [FIX] 캘린더 수정
  src/main/java/com/newstoss/calender/Calendar.java
  src/main/java/com/newstoss/calender/CalendarController.java
  src/main/java/com/newstoss/calender/CalendarRepository.java
Labels: 🐛 fix, 장우

#183 [FIX] 챗봇 쓰레드 풀 갯수 지정
  src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/RealTimeNewsDTO.java
  src/main/java/com/newstoss/news/adapter/out/redis/subscriber/ChatRedisSubscriber.java
Labels: 🐛 fix, 준영

#185 [FIX] dto수정
  src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/RealTimeNewsDTO.java
Labels: 🐛 fix, 준영

#186 [TEST] 시간 로그 추가
  src/main/java/com/newstoss/news/adapter/in/web/sse/controller/SseController.java
  src/main/java/com/newstoss/news/adapter/out/redis/highlight/HighlightNewsScheduler.java
  src/main/java/com/newstoss/news/adapter/out/redis/realtime/RealTimeNewsCache.java
  src/main/java/com/newstoss/news/adapter/out/redis/subscriber/ChatRedisSubscriber.java
  src/main/java/com/newstoss/news/application/redis/RealTimeService.java
  src/main/java/com/newstoss/news/application/redis/impl/HighlightNewsCacheImpl.java
  src/main/java/com/newstoss/news/application/redis/impl/RealTimeNewsCacheImpl.java
  src/main/java/com/newstoss/news/application/redis/port/in/RealTimeNewsCacheUseCase.java
  src/main/java/com/newstoss/news/application/redis/port/out/RealTimeNewsCachePort.java
Labels: 🧪 test, 준영

#188 [FIX] 빈 이름 중복 제거
  src/main/java/com/newstoss/news/adapter/out/redis/highlight/HighlightNewsCache.java
  src/main/java/com/newstoss/news/adapter/out/redis/realtime/RealTimeNewsCache.java
  src/main/java/com/newstoss/news/application/redis/impl/RealTimeNewsCacheImpl.java
  src/main/java/com/newstoss/news/application/redis/port/in/RealTimeNewsCacheUseCase.java
  src/main/java/com/newstoss/news/application/redis/port/out/RealTimeNewsCachePort.java
Labels: 🐛 fix, 준영

#189 [FIX] 에러 로그 세분화
  src/main/java/com/newstoss/news/adapter/out/news/v2/MLNewsAdapterV2.java
Labels: 🐛 fix, 준영

#190 [FIX] 뉴스 DTO 수정
  src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/HighlightNewsDTO.java
  src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/Meta/RelatedNewsDTOv2.java
  src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/NewsDTOv2.java
  src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/RecommendNewsDTO.java
  src/main/java/com/newstoss/news/adapter/in/web/scrap/dto/LogNewsDTO.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/controller/SseController.java
  src/main/java/com/newstoss/news/adapter/out/news/dto/v2/MLHighlightNewsDTOv2.java
  src/main/java/com/newstoss/news/adapter/out/news/dto/v2/MLNewsDTOv2.java
  src/main/java/com/newstoss/news/adapter/out/news/dto/v2/MLRecommendNewsDTO.java
  src/main/java/com/newstoss/news/adapter/out/news/dto/v2/MLRelatedNewsDTOv2.java
  src/main/java/com/newstoss/news/application/news/v2/impl/NewsDTOv2Mapper.java
  src/main/java/com/newstoss/news/application/scrap/impl/GetScrapNewsList.java
Labels: 🐛 fix, 준영

#191 뉴스 갯수 api 생성 및 커넥션 풀 설정
  build.gradle
  src/main/java/com/newstoss/global/config/MLRestTemplateConfig.java
  src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java
  src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/CountDTO.java
  src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/NewsDTOv2.java
  src/main/java/com/newstoss/news/adapter/in/web/sse/controller/SseController.java
  src/main/java/com/newstoss/news/adapter/out/news/dto/v2/MLNewsCountDTO.java
  src/main/java/com/newstoss/news/adapter/out/news/dto/v2/MLNewsDTOv2.java
  src/main/java/com/newstoss/news/adapter/out/news/v2/MLNewsAdapterV2.java
  src/main/java/com/newstoss/news/application/news/service/NewsServiceV2.java
  src/main/java/com/newstoss/news/application/news/v2/impl/NewsDTOv2Mapper.java
  src/main/java/com/newstoss/news/application/news/v2/impl/ml/GetNewsCount.java
  src/main/java/com/newstoss/news/application/news/v2/port/in/GetNewsCountUseCaseV2.java
  src/main/java/com/newstoss/news/application/news/v2/port/out/MLNewsPortV2.java
Labels: 🐛 fix, ✨ feature, 준영

#192 [FEAT] 뉴스 로그 api 생성, 기존 상세 뉴스 조회에서 로그 기능 제거
  src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV2.java
  src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsLogsController.java
  src/main/java/com/newstoss/news/application/news/service/NewsLogRecordService.java
  src/main/java/com/newstoss/news/application/news/service/NewsServiceV2.java
  src/main/java/com/newstoss/news/application/news/v2/impl/ml/GetDetailNewsV2.java
  src/main/java/com/newstoss/news/application/news/v2/port/in/GetNewsDetailUseCaseV2.java
Labels: ✨ feature, 장우

#193 [FIX] 실시간 뉴스 DTO 수정
  src/main/java/com/newstoss/news/adapter/in/web/news/dto/v2/RealTimeNewsDTO.java
Labels: 🐛 fix, 준영

#195 [TEST] log 메세지 수정
  src/main/java/com/newstoss/news/adapter/out/news/v2/MLNewsAdapterV2.java
  src/main/java/com/newstoss/news/adapter/out/redis/subscriber/ChatRedisSubscriber.java
  src/main/java/com/newstoss/news/application/redis/ChatStreamService.java
Labels: 🧪 test, 준영

#197 [FIX] 챗봇 서버 변경
  src/main/java/com/newstoss/global/config/MLWebClientConfig.java
  src/main/java/com/newstoss/news/adapter/out/redis/subscriber/ChatRedisSubscriber.java
Labels: 🐛 fix, 준영

#200 [FIX] jwt 수정
  src/main/java/com/newstoss/auth/adapter/in/web/AuthController.java
  src/main/java/com/newstoss/auth/application/AuthService.java
  src/main/java/com/newstoss/auth/application/command/RefreshService.java
  src/main/java/com/newstoss/global/config/SecurityConfig.java
  src/main/java/com/newstoss/global/jwt/JwtAuthenticationFilter.java
  src/main/java/com/newstoss/global/jwt/JwtResolver.java
  src/main/java/com/newstoss/member/application/in/command/CustomUserDetailsService.java
  src/main/java/com/newstoss/member/application/in/command/InvestScoreService.java
  src/main/java/com/newstoss/member/domain/UserAccount.java
  src/main/java/com/newstoss/news/application/news/service/NewsLogRecordService.java
Labels: 🐛 fix, 준영

#202 [FIX] 캘린더, 관심 그룹 swagger 추가
  src/main/java/com/newstoss/calender/CalendarController.java
  src/main/java/com/newstoss/favorite/FavoriteGroup/FavoriteController.java
Labels: 🐛 fix, 장우

#203 [FIX] Tag, opration 추가
  src/main/java/com/newstoss/auth/adapter/in/web/AuthController.java
  src/main/java/com/newstoss/member/adapter/in/web/MemberController.java
  src/main/java/com/newstoss/news/adapter/in/web/news/controller/NewsControllerV1.java
Labels: 🐛 fix, 준영

#204 [FIX] 관심 그룹 삭제하면 안의 관심 종목도 제거
  src/main/java/com/newstoss/favorite/FavoriteGroup/Favorite.java
  src/main/java/com/newstoss/favorite/FavoriteGroup/FavoriteService.java
  src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStock.java
  src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStockRepository.java
Labels: 🐛 fix, 장우

#205 Fix : 관심그룹 버그 수정
  src/main/java/com/newstoss/favorite/FavoriteGroup/Favorite.java
  src/main/java/com/newstoss/favorite/FavoriteGroup/FavoriteRepository.java
  src/main/java/com/newstoss/favorite/FavoriteGroup/FavoriteService.java
  src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStock.java
Labels: 🐛 fix, 장우

#206 [FIX] 모든 유저 정보조회 수정
  src/main/java/com/newstoss/member/adapter/out/persistence/JpaMemberInfoRepositoryImpl.java
Labels: 🐛 fix, 장우

#207 [FIX] 증권 API에서 값 불러오도록 수정
  src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStock.java
  src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStockController.java
  src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStockRepository.java
  src/main/java/com/newstoss/favorite/FavoriteStock/FavoriteStockService.java
  src/main/java/com/newstoss/favorite/adapter/out/ExternalStockApiClient.java
  src/main/java/com/newstoss/favorite/adapter/out/dto/ExternalStockApiResponse.java
  src/main/java/com/newstoss/global/errorcode/FavoriteErrorCode.java
Labels: 🐛 fix, 장우
